[package]
name = "ningyo-render-wgpu"
description = "WGPU renderer for Inox2D"
authors = ["Arcturus Emrys <aemrys@arcturus.live>"]
version = "0.3.0"
edition = "2024"
license = "BSD-2-Clause"
keywords = ["gamedev", "graphics", "inochi2d", "vtuber", "opengl"]
categories = ["graphics", "rendering"]

[dependencies]
inox2d = { git = "https://github.com/ArcturusEmrys/inox2d", rev = "c672d35f364f7df36f1f167d655539e59abc18c2" }
glam = "0.29.0"
wgpu-hal = { version = "29.0.0" }
wgpu = { version = "29.0.0", features=["spirv"] }
thiserror = "1.0.39"
ningyo-extensions = { path="../ningyo-extensions" }
wgpu-profiler = { version = "0.27.0", optional=true }
tracy-client = { version = "0.18.4", optional=true }

[build-dependencies]
shaderc = { version = "0.10", features=["build-from-source"] }
spirv-reflect = { git = "https://github.com/gwihlidal/spirv-reflect-rs.git", rev="97298067e3b1c9ce05633d78f1183c14a3cc6acc"}

[features]
tracy = [
    "dep:wgpu-profiler",
    "dep:tracy-client",
    "wgpu-profiler/tracy",
    "tracy-client/enable",
    "tracy-client/callstack-inlines",
    "tracy-client/sampling",
    "tracy-client/system-tracing"
]