[package]
name = "puppet-inspector"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
authors = ["Arcturus Emrys <aemrys@arcturus.live>"]

[dependencies]
glib = { version = "0.22.0" }
gio = { version = "0.22.1" }
inox2d = { git = "https://github.com/ArcturusEmrys/inox2d", rev = "9d48bc1fb76a72b608f283efaba1b07caff95010" }
inox2d-opengl = { git = "https://github.com/ArcturusEmrys/inox2d", rev = "9d48bc1fb76a72b608f283efaba1b07caff95010" }
json = "0.12.4"
gl46 = "0.2.1"
glam = "0.29.0"
ningyo-look-and-feel = { path = "../ningyo-look-and-feel", optional=true }
ningyo-extensions = { path = "../ningyo-extensions" }
ningyo-gtk-wgpu = { path = "../ningyo-gtk-wgpu" }
ningyo-render-wgpu = { path = "../ningyo-render-wgpu" }
wgpu = { version = "29.0.0" }

[target.'cfg(not(windows))'.dependencies]
gtk4 = { version = "0.11.0", features = ["v4_10"] }
gdk4 = { version = "0.11.0", features = ["v4_10"] }

[target.'cfg(windows)'.dependencies]
gtk4 = { version = "0.11.0", features = ["v4_20"] }
gdk4 = { version = "0.11.0", features = ["v4_20"] }

[build-dependencies]
glib-build-tools = "0.22.0"

[target.'cfg(target_os="windows")'.build-dependencies]
ico = "0.5.0"
winresource = "0.1.31"

[features]
branding = ["dep:ningyo-look-and-feel"]