name: Build

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest']

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      if: matrix.os == "windows-latest"
      run: cargo build --verbose

    - name: Build
      if: matrix.os != "windows-latest"
      run: cargo build --verbose --workspace --exclude ningyo-spout2
    
    - name: Run tests
      if: matrix.os == "windows-latest"
      run: cargo build --verbose
    
    - name: Run tests
      if: matrix.os != "windows-latest"
      run: cargo build --verbose --workspace --exclude ningyo-spout2