name: Build

on:
  push:
    branches: [ 'main', 'master' ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  packages: write
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os:
          - name: 'windows-latest'
            compatible_features: 'ningyotsukai/spout,ningyotsukai/timing,ningyotsukai/tracy,ningyotsukai/renderdoc,ningyotsukai/branding,puppet-inspector/branding'
            flags: ''
          - name: 'ubuntu-latest'
            compatible_features: 'ningyotsukai/pipewire,ningyotsukai/timing,ningyotsukai/tracy,ningyotsukai/renderdoc,ningyotsukai/branding,puppet-inspector/branding'
            flags: '--exclude ningyo-spout2'

    runs-on: ${{matrix.os.name}}

    steps:
    - uses: actions/checkout@v4
    
    - name: Cache native dependencies (Windows)
      if: matrix.os.name == 'windows-latest'
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" `
          --name "GitHubPackages" `
          --username "${{ github.repository_owner }}" `
          --password "${{ secrets.GITHUB_TOKEN }}" `
          --store-password-in-clear-text
    
    - name: Cache compiled Rust
      uses: swatinem/rust-cache@v2
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-x86_64

    - name: Install Dependencies (Ubuntu)
      if: matrix.os.name == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get -y install libgtk-4-dev libpipewire-0.3-dev

    - name: Install Dependencies (Windows)
      if: matrix.os.name == 'windows-latest'
      env:
        VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json,readwrite"
      run: |
        vcpkg install --triplet=x64-windows

        echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" >> $env:GITHUB_ENV
        echo "RUST_VCPKG_DEFAULT_BINARIES=1" >> $env:GITHUB_ENV
        echo "PKG_CONFIG_PATH=${{ github.workspace }}\vcpkg_installed\x64-windows\lib\pkgconfig" >> $env:GITHUB_ENV
        echo "GTK_LIB_DIR=${{ github.workspace }}\vcpkg_installed\x64-windows\lib" >> $env:GITHUB_ENV
        echo "PKG_CONFIG=${{ github.workspace }}\vcpkg_installed\x64-windows\tools\pkgconf\pkgconf.exe" >> $env:GITHUB_ENV
        echo "${{ github.workspace }}\vcpkg_installed\x64-windows\bin" >> $env:GITHUB_PATH
        echo "${{ github.workspace }}\vcpkg_installed\x64-windows\tools\pkgconf" >> $env:GITHUB_PATH
        echo "${{ github.workspace }}\vcpkg_installed\x64-windows\tools\glib" >> $env:GITHUB_PATH
    
    - name: Build baseline
      run: cargo build --verbose --workspace ${{ matrix.os.flags }}
    
    - name: Build with features
      run: cargo build --verbose --workspace ${{ matrix.os.flags }} --features ${{ matrix.os.compatible_features }}
    
    - name: Run tests
      run: cargo test --verbose --workspace ${{ matrix.os.flags }} --features ${{ matrix.os.compatible_features }}